
################ Optimizer #############################################################################################
optimizer:
  type: "Adam"
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.00001
lr:
  ae:      0.01
  dis_app: 0.01
  dis_pla: 0.01
  scheduler:
    type: "none"

################ Network ###############################################################################################
weight_recon:   1.0   # DO NOT MODIFIED
weight_dis_app: 0.1
weight_dis_pla: 0.3
recon_loss_type: "L2"
gan_type: "lsgan"
num_critic: 1
weight_gp: 10.0
weight_div: 10.0
denoise: false
smooth_label: false

################ Training ##############################################################################################
gpu: "cuda:3"
evaluate_only: false
batch-size: 256
epochs: 75
workers: 8
checkpoint: ''
seed: 0

################ Logging ###############################################################################################
log_dir: "logs/gaussian_2d_a-2"
model_name: "wdis-0.1"
eval_mode: "step"
eval_interval: 50
eval_batch: 2
save_model_interval: 10000000000000
# log option: 'none', 'file', 'tb' or 'pyplot'
log:
  grad_histogram: "none"
  viz_2d: "pyplot"
  correlation: "none"
  feature: "none"
  pr: "none"
  transform_image: "none"
place_threshold: 3

################ Dataset ###############################################################################################
dataset_type: "GaussianND"
dim_x: 10
dim_enc_s: 2
dim_enc_a: 2
mean_s: [0.0, 2.0]
mean_a1: [+1.0, +1.5]
mean_a2: [-1.0, -1.5]
std_s: [0.2, 0.2]
std_a: [0.2]