
################ Optimizer #############################################################################################
optimizer:
  type: "Adam"
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.00001
lr:
  ae:      0.0001
  dis_app: 0.0002
  dis_pla: 0.0002
  scheduler:
    type: "none"

################ Network ###############################################################################################
weight_recon:   1.0   # DO NOT MODIFIED
weight_dis_app: 0.00000001
weight_dis_pla: 0.00000001
recon_loss_type: "L2"
gan_type: "lsgan"
num_critic: 1
weight_gp: 10.0
weight_div: 10.0
denoise: false
smooth_label: false

################ Training ##############################################################################################
gpu: "cuda:3"
evaluate_only: false
batch-size: 256
epochs: 350
workers: 8
checkpoint: ''
seed: 0

################ Logging ###############################################################################################
log_dir: "logs/gaussian_nd"
model_name: "wdis-0.00000001"
eval_mode: "step"
eval_interval: 200
eval_batch: 1000000
save_model_interval: 10000000000000
# log option: 'none', 'file', 'tb' or 'pyplot'
log:
  grad_histogram: "tb"
  viz_2d: "none"
  correlation: "file"
  feature: "none"
  pr: "none"
  transform_image: "none"
place_threshold: 3

################ Dataset ###############################################################################################
dataset_type: "GaussianND"
dim_x: 50
dim_enc_s: 5
dim_enc_a: 5
mean_s: [-0.3, -0.1, 0.1, 0.3, 0.5]
std_s: [0.1, 0.1, 0.1, 0.1, 0.1]
mean_a: [-0.4, -0.2, 0.0, 0.2, 0.4]
std_a: [0.1, 0.1, 0.1, 0.1, 0.1]