
################ Optimizer #############################################################################################
optimizer:
  type: "Adam"
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.00001
lr:
  ae:      0.000024
  dis_app: 0.00008
  dis_pla: 0.00008
  scheduler:
    type: "none"

################ Network ###############################################################################################
weight_recon:   1.0   # DO NOT MODIFIED
weight_dis_app: 0.024
weight_dis_pla: 0.08
recon_loss_type: "L2"
gan_type: "lsgan"
num_critic: 1
weight_gp: 10.0
weight_div: 10.0
denoise: false
smooth_label: false

################ Training ##############################################################################################
gpu: "cuda:3"
evaluate_only: true
batch-size: 16
epochs: 100
workers: 4
checkpoint: "/home/tangli/Data/fdn-pr/logs/pr/nordland-2doms-winter-spring/1563555370.445039/train/model-99-1035.pth"
# seed: 0

################ Logging ###############################################################################################
log_dir: "logs/tnnls/new_arch"
model_name: 'lsgan_lr-ae-0.000024-dis-0.00008_weight-dis-app-0.024_weight-dis-pla-0.08_spring-summer'
eval_mode: "step"
eval_interval: 1500
eval_batch: 1000000000000000
save_model_interval: 1500
# log option: 'none', 'file', 'tb' or 'pyplot'
log:
  grad_histogram: "tb"
  viz_2d: "none"
  correlation: "none"
  feature: "none"
  pr: "file"
  transform_image: "file"
place_threshold: 3

################ Dataset ###############################################################################################
dataset_type: 'PlaceRecognition'
augmentation: true
train_data_dir:
  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/spring_images_train'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/summer_images_train'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/fall_images_train'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/winter_images_train'

#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/spring_images_train'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/summer_images_train'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/fall_images_train'
  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/train/winter_images_train'

eval_data_dir: # Database vs Query
  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/spring_images_test'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/summer_images_test'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/fall_images_test'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/winter_images_test'

#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/spring_images_test'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/summer_images_test'
#  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/fall_images_test'
  - '/home/tangli/Data/datasets/Partitioned_Nordland_Dataset_lowres/Dataset_images/test/winter_images_test'