
################ Optimizer #############################################################################################
optimizer:
  type: "Adam"
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.00001
lr:
  ae:      0.000003
  dis_app: 0.00001
  dis_pla: 0.00001
  scheduler:
    type: "none"

################ Network ###############################################################################################
weight_recon:   1.0   # DO NOT MODIFIED
weight_dis_app: 0.003
weight_dis_pla: 0.01
recon_loss_type: "L2"
gan_type: "lsgan"
num_critic: 1
weight_gp: 10.0
weight_div: 10.0
denoise: false
smooth_label: false

################ Training ##############################################################################################
gpu: "auto"
evaluate_only: false
batch-size: 16
epochs: 200
workers: 4
checkpoint: ""
seed: 0

################ Logging ###############################################################################################
<<<<<<< HEAD
log_dir: "logs/final/2doms"
=======
log_dir: "/logs/final/4doms"
>>>>>>> 5191d509d862c078ca192db7cb2623ad5c3e39b5
model_name: '<model_name>'
eval_mode: "step"
eval_interval: 1500
eval_batch: 1000000000000000
save_model_mode: 'epoch'
save_model_interval: 20
# log option: 'none', 'file', 'tb' or 'pyplot'
log:
  grad_histogram: "none"
  viz_2d: "none"
  correlation: "none"
  feature: "none"
  pr: "file"
  pr_match: "file"
  transform_image: "none"
place_threshold: 3

################ Dataset ###############################################################################################
dataset_type: 'PlaceRecognition'
augmentation: true
train_data_dir: []

eval_data_dir: []
